# gz-sim8-config.cmake (generated by upstream gz-sim's CMake package
# config machinery) calls find_package(gz-gui8) before find_package(Qt5),
# even though gz-gui8's exported targets link against Qt5::Core -- a real
# ordering bug in that generated file, not something in PX4's own source.
# Pre-resolving Qt5's imported targets here, via CMAKE_PROJECT_INCLUDE
# (runs right after PX4's own top-level project() call, before
# src/modules/simulation/gz_plugins/CMakeLists.txt's find_package(gz-sim8)
# is ever reached), works around it without patching generated gz-cmake
# output. specs/007-sitl-gazebo-ros2.md REQ-2.
find_package(Qt5 COMPONENTS Core Quick QuickControls2 REQUIRED)
