[General]
   TcpServerPort=5760
   ReportStats=false
   MavlinkDialect=common

# -----------------------------------------------------------------------------
# Uncomment this block for PX4 connections over serial (UART/USB targets)
# [UartEndpoint fromPX4serial]
#   Device=/dev/ttyPX4
#   Baud=2000000

# -----------------------------------------------------------------------------
# This endpoint can be used for SITL or ethernet connects to PX4
# For SITL on host with tap network,to stop all mavlink connections and start 
# with:
#    pxh> mavlink stop-all
#    pxh> mavlink start -u 14540 -o 14540 -t 192.168.7.2
#
# Note: if hardware target is used, blcok-comment the [UdpEndpoint fromPX4network] 
#       endpoint below
[UdpEndpoint fromPX4network]
   Mode=server
   Address=0.0.0.0
   Port=14540

# -----------------------------------------------------------------------------
# Let clients connect to this endpoint
[UdpEndpoint toClients]
   Mode=server
   Address=0.0.0.0
   Port=14550
